### ISSUE TITLE
ValueError: x and y must have same first dimension, but have shapes (118,) and (134,)

### ISSUE THREAD

**Issue by pnerella18** [IBM/coursera#10]
Tried to create a run chart using two lists - but held back due to sample data returned in second query is not consistent -

result = spark.sql("select temperature from washing where temperature is not null")
print(result.count())
result_array = result.rdd.map(lambda row : row.temperature).sample(False,0.1).collect()
len(result_array)

**printed below as expected -
1342
134

result_ts = spark.sql("select ts from washing where temperature is not null")
print(result_ts)
result_array_ts = result_ts.rdd.map(lambda row : row.ts).sample(False,0.1).collect()
len(result_array_ts)
** Was able to verify result_ts as '1342'  but  sample is not giving 10% of given data,  i.e. result_array_ts returned 118 records 

plt.plot(result_array_ts,result_array)
plt.xlabel("time")
plt.ylabel("temperature")
plt.show()
** failed to create run chart with the error mentioned 
"ValueError: x and y must have same first dimension, but have shapes (118,) and (134,)"

**Comment by romeokienzler** [comment]
please use the coursera forum, thanks a lot, this is for errors in my code, not yours :)
