### ISSUE TITLE
Unable to use system ml 1.3 snapshot for coursera Advanced ML and signal processing course.

### ISSUE THREAD

**Issue by fulcrum3** [IBM/coursera#15]
@romeokienzler  pip installing this package isn't leading to a system ml version upgrade in the watson studio. 
 [https://github.com/IBM/coursera/blob/master/systemml-1.3.0-SNAPSHOT-python.tar.gz](https://github.com/IBM/coursera/blob/master/systemml-1.3.0-SNAPSHOT-python.tar.gz)
Please refer to the following thread on [coursera](https://www.coursera.org/learn/advanced-machine-learning-signal-processing/discussions/weeks/4/threads/Q1QUXtYdEem7XwoK5oxU8g)

**Comment by romeokienzler** [comment]
thanks a lot! [x] fixed (in the template)
