### ISSUE TITLE
Runtime for Notebook (Step 3 of Environment Setup)

### ISSUE THREAD

**Issue by arjunmann73** [IBM/coursera#16]
Python version 3.5 1vCPU and 4GB ram isn't an option anymore.
Either I am doing something wrong or maybe the setup tutorial needs to be updated.

Regards,
Arjun

**Comment by romeokienzler** [comment]
please use the Coursera discussion forum for such type of questions, I think you can use the 3.6 default 1 vCPU / 4 GB runtime
