### ISSUE TITLE
Downloading the file problem

### ISSUE THREAD

**Issue by Vijay552** [IBM/coursera#19]
Hi, 
I have problem downloading the file into my local jupyter notebooks by using pyspark. Can you please helpme.
Thanks,

**Comment by Vijay552** [comment]
What is the command to download the file from this link: "https://github.com/IBM/coursera/raw/master/hmp.parquet"

**Comment by Vijay552** [comment]
I have tried using the following code"
df = spark.read.load("https://github.com/IBM/coursera/raw/master/hmp.parquet")

**Comment by romeokienzler** [comment]
spark doesn't support direct https downloads, please download the file manually or use the
!wget 
or
!curl

command
