### ISSUE TITLE
Got "IndexError: list index out of range" when following spark_setup_anaconda.ipynb

### ISSUE THREAD

**Issue by wyfok** [IBM/coursera#29]
At first intended to install spark into the local computer and so ran the code provided from spark_setup_anaconda.ipynb to install Spark. However, got "IndexError: list index out of range"

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-9ce334a2b91d> in <module>
      8 os.environ["SPARK_HOME"] = "/home/dsxuser/work/spark-2.3.4-bin-hadoop2.7"
      9 import findspark
---> 10 findspark.init()
     11 from pyspark import SparkContext, SparkConf
     12 from pyspark.sql import SQLContext, SparkSession

~\Anaconda3\lib\site-packages\findspark.py in init(spark_home, python_path, edit_rc, edit_profile)
    133     # add pyspark to sys.path
    134     spark_python = os.path.join(spark_home, 'python')
--> 135     py4j = glob(os.path.join(spark_python, 'lib', 'py4j-*.zip'))[0]
    136     sys.path[:0] = [spark_python, py4j]
    137 

IndexError: list index out of range`

**Comment by romeokienzler** [comment]
thanks a lot! [x] fixed
