### ISSUE TITLE
: A question and require your guidance on the Course : Advanced Data Science with IBM Specialization on Coursera

### ISSUE THREAD

**Issue by SriramanK1** [IBM/coursera#9]
I have enrolled for the course Advanced Data Science with IBM specialization and completed Week 1 through 4 partially. https://www.coursera.org/specializations/advanced-data-science-ibm

Please note, I am a new to coding person with only minimal knowledge on Phyton - based on my course on www.cognitiveclass.ai.

In this, on week 2, 3, when try to complete the programming assignments on Spark and tried to set up and learn, I am stuck. Unfortunately, the guidelines video hosted here : [](https://www.youtube.com/watch?v=JSnrsXSTE9U) is also not available / working.

I have also posted this query on the discussions forum there in Coursera last week and awaiting advise. 
Ref : https://www.coursera.org/learn/ds/discussions/weeks/2/threads/Y40fZ4hDEemB1RILjckZRA

However I am worried that I might loose time in this process.

In fact, I require advise on how and where to start the environment and continue.

Could you please guide and advise me for successful learning of this course.

**Comment by romeokienzler** [comment]
Answered in the Coursera thread
